name: Push to spring-106 mirror

on:
  workflow_dispatch:
  push:
    branches:
      - 'spring-106'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone branch
        run: |
          git clone -b spring-106 https://github.com/CommanderSpice/mirrortest-orig.git
      - name: Push to mirror
        run: |
          git -C mirrortest-orig push --tags --atomic --force https://CommanderSpice:${{ secrets.API_TOKEN_GITHUB }}@github.com/CommanderSpice/mirrortest-mirror.git spring-106:master
